version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: crud-postgres-ps
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=\
      - POSTGRES_PASSWORD=\
      - POSTGRES_DB=\
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
